### ISSUE TITLE
Psych::BadAlias in Ruby 3.1 configuration

### ISSUE THREAD

**Issue by negipo** [sunspot/sunspot#1022]
We have an app with
- sunspot_rails (2.6.0)
- rails (6.1.7)
- ruby (3.1.3)

When I create configuration like:
```yaml
base: &base
  solr:
    hostname: 127.0.0.1
    port: 8983
    path: /solr/sunspot
  master_solr:
    hostname: 127.0.0.1
    port: 8983
    path: /solr/sunspot

development:
  <<: *base

test:
  <<: *base
```

Makes `Unknown alias: base (Psych::BadAlias)`
[stacktrace](https://gist.github.com/negipo/3727ac90ef0fbb56cc26452b85fafa62)

This is because Psych 4.0.0 goes safe mode by default in Ruby 3.1.
I found some fixes for similar problem in other projects:
- `YAML.unsafe_load` in rails https://github.com/rails/rails/pull/42257
- `YAML.safe_load(..., aliases: true)` in sidekiq https://github.com/mperham/sidekiq/pull/5141
