### ISSUE TITLE
Sunspot Solr configs should default to multi-core setup vs. multi-port

### ISSUE THREAD

**Issue by nz** [sunspot/sunspot#115]
# Solr directory structure

```
- solr/
  - conf/
    - schema.xml
    - solrconfig.xml
    - etc…
  - development/
    - conf -> ../conf
  - production
    - conf -> ../conf
  - test/
    - conf -> ../conf
  - solr.xml
```
## solr/solr.xml

``` xml
<solr persistent="true" sharedLib="lib">
  <cores adminPath="/admin/cores">
    <core name="production"  instanceDir="production" />
    <core name="development" instanceDir="development" />
    <core name="test"        instanceDir="test" />
  </cores>
</solr>
```
## config/sunspot.yml

``` yml
production:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/production
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/development
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/test
    log_level: WARNING
```
