### ISSUE TITLE
Sunspot committing despite disabled auto commit

### ISSUE THREAD

**Issue by jure** [sunspot/sunspot#231]
We just started using sunspot on a fairly large site and while development with it has been a blast, I'm running into some issues now that it is in production.

Although I've set committing after requests to false in sunspot.yml, I'm still seeing a large number of commits in the Solr logs. As we are reindexing at the moment, you can imagine how annoying it is to have 20 commits per minute disturbing this process.

```
  master_solr:
    hostname: swordfish.example.com
    port: 8983
    log_level: WARNING
    auto_commit_after_request: false
    auto_commit_after_delete_request: false
  solr:
    hostname: turtle.example.com
    port: 8983
    log_level: WARNING
    auto_commit_after_request: false
    auto_commit_after_delete_request: false
```

I have autoCommit disabled in solrconfig.xml, and the commits I'm seeing are commits, not autocommits. 

I am also using sunspot-rails-failover, but I've commented it's commit method body, so that can't possibly be it.

How can I stop sunspot from issuing commits? And why is it doing that despite the setting?
