### ISSUE TITLE
Sunspot still performing commit with auto_commit_after_request: false

### ISSUE THREAD

**Issue by navied** [sunspot/sunspot#523]
It seems like it sunspot is still committing even though auto_commit_after_request is set to false. I simply check by manually indexing something then searching for it right away.

**Comment by styrmis** [comment]
If you are using Solr 4.x then it is possible that this is happening due to the [Near Real Time Search](https://cwiki.apache.org/confluence/display/solr/Near+Real+Time+Searching) feature, which allows you to search for documents that have been indexed but have not yet been (hard) committed.

Could you post your `sunspot.yml` file? I believe the `auto_commit_after_request` setting needs to be set at the top level (i.e. not within an environment like you might expect) for it to take effect; that is another possibility for why the setting isn't taking effect.

**Comment by navied** [comment]
I ended up making a slave-master Solr to fix this problem and used the slave to make reads and did a copy from the master once a day since the data was not extremely important to be constantly updated. My sunspot.yml file before I did this change would look the same with master_solr removed:

```
production:
  solr:
    hostname: x.x.x.x
    port: 8080
    log_level: WARNING
    path: '/solr/collection1'
    read_timeout: 15
    open_timeout: 2.0
  master_solr:
    hostname: x.x.x.x
    port: 8080
    log_level: WARNING
    path: '/solr/collection1'
    read_timeout: 15
    open_timeout: 2.0
  auto_commit_after_request: false

staging:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr'
    log_level: WARNING
  auto_commit_after_request: false

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr
    read_timeout: 10
    open_timeout: .5
  auto_commit_after_request: false

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    
```
