### ISSUE TITLE
Ability to add multiple nodes to sunspot.yml (e.g. when using SolrCloud)

### ISSUE THREAD

**Issue by heaven** [sunspot/sunspot#608]
Hello,

We have SolrCloud setup and a few physical servers, ones run shards and others — replicas for them. The problem is in that we can only add a single IP to the sunspot.yml and if we need to reboot that Solr node search becomes unavailable.

It would be really great to have an ability to specify an array of nodes. For SolrCloud there's no difference which node receives requests so both reads and updates could be sent to any. The benefit is in that we can specify IPs of different physical servers and in case if one of them fails (with a timeout) we can try another node and raise an error if none of specified nodes respond in time.

Best,
Alexander

**Comment by iRonin** [comment]
+1

**Comment by itsmechlark** [comment]
+1

**Comment by heaven** [comment]
New pull: https://github.com/sunspot/sunspot/pull/796

**Comment by Stex** [comment]
:+1:

@heaven: Thanks for you work here regarding solrcloud!

Probably a stupid question, but how would a sunspot configuration currently have to look when using 1 shard with 4 nodes regarding the port sunspot uses? I haven't really found anything in the documentation.

From my understanding, I may simply point it to the master node which will then balance the requests, but I'm not sure whether it's actually working.
Thanks in advance!

**Comment by heaven** [comment]
Hey, here's our production example:
```yaml
production:
  solr:
    hosts:
      - 'solr1.devops:8080/solr/crm-prod'
      - 'solr1.devops:8081/solr/crm-prod'
      - 'solr1.devops:8082/solr/crm-prod'
      - 'solr1.devops:8083/solr/crm-prod'
      - 'solr2.devops:8080/solr/crm-prod'
      - 'solr2.devops:8081/solr/crm-prod'
      - 'solr2.devops:8082/solr/crm-prod'
      - 'solr2.devops:8083/solr/crm-prod'
    read_timeout: 60
    open_timeout: 3
    log_level: WARNING
```

I didn't add this to README because this depends or RSolr patch I've also submitted (https://github.com/rsolr/rsolr/pull/138) and it wasn't merged yet.

You can also specify `master_hosts` array the same way.

I will close this pull for now, here's the new one with resolved conflicts: https://github.com/sunspot/sunspot/pull/796
