### ISSUE TITLE
specifying path in sunspot.yml not working

### ISSUE THREAD

**Issue by eugenekorpan** [sunspot/sunspot#707]
Hi there,
I think I have already seen some workarounds in the net but I think this should be fixed.
Here is my `sunspot.yml` config file
```
production:
  solr:
    hostname: localhost
    post: 8983
    log_level: WARNING
    path: /srv/www/myschool_app/shared/solr
    pid_dir: /srv/www/myschool_app/shared/solr/pids

```

after running `rake sunspot:solr:start` I get this
```
1352 ?        Ssl    0:11 java -Djetty.port=8983 -Dsolr.data.dir=/srv/www/myschool_app/releases/20150626083851/solr/data/production -Dsolr.solr.home=/srv/www/myschool_app/releases/20150626083851/solr -Djava.util.logging.config.file=/tmp/logging.properties20150626-1352-1lalf2m -Djava.awt.headless=true -jar start.jar

```

when go to that path I see nothing
```
[root@myschool411 data]# cd /srv/www/myschool_app/shared/solr/
[root@myschool411 solr]# ls
data  pids
[root@myschool411 solr]# cd data
[root@myschool411 data]# ls
[root@myschool411 data]# 

```

the indexes are actually stored in the app root
```
[root@myschool411 data]# cd /srv/www/myschool_app/current/solr/default/data/
[root@myschool411 data]# ls
index  tlog
```

so did I miss something with `path` option or how can I set directory to store the indexes?
