### ISSUE TITLE
Multicore setup

### ISSUE THREAD

**Issue by DaniG2k** [sunspot/sunspot#728]
Hello all. It is not clear to me from the documentation how to make a multi-core (2 + Rails apps, 1 Solr instance) setup. Is there a guide that I've missed here?

Thanks!

**Comment by sriramg** [comment]
We do this today (with sunspot 2.2 and Solr 4.1) -- we have one solr server with 8 collections serving 8 different rails apps -- we simply point sunspot.yml to the appropriate collection:

sunspot.yml example:
```
staging:
  solr:
    hostname: 10.230.88.201
    port: 8983
    log_level: WARNING
    path: /solr/collectionh
```
