### ISSUE TITLE
undefined method `facet' for #<Sunspot::Search:

### ISSUE THREAD

**Issue by acprsadmin** [sunspot/sunspot#766]
Trying to make the faceting work on this application using Sunspot.

model:

```
searchable do
      text :title, :boost => 5
      text :body
      integer :technicalarea_ids, :references => Technicalarea, :multiple => true
      integer :targetgroup_ids, :references => Targetgroup, :multiple => true
      integer :organization_id, :references => Organization
      integer :series_id, :references => Series


     I18n.available_locales.each do |locale|
       # Separate name field for each locale
       text "title_#{locale}".to_sym do
         # read_Attribute is defined by Globalize.
         read_attribute(:title, locale: locale)
       end
       text "body_#{locale}".to_sym do
         read_attribute(:body, locale: locale)
       end
     end
     string :publish_month
  end
```

controller:

 ```
def results
   search = Resource.search do
      fulltext params[:search_term]
     if !params[:technicalarea_ids].nil?
        with(:technicalarea_ids, params[:technicalarea_ids].reject(&:blank?))
      end
      if !params[:targetgroup_ids].nil?
        with(:targetgroup_ids, params[:targetgroup_ids].reject(&:blank?))
      end
      if !params[:organization_ids].nil?
        with(:organization_id, params[:organization_ids].reject(&:blank?))
      end
      if !params[:series_ids].nil?
        with(:series_id,  params[:series_ids].reject(&:blank?))
      end

      facet :organization_id


    end

    @search = search.results
    render 'visitors/search_results'
  end
```
view:
```

 <% @search.facet(:organization_id).rows.each do |row| %>
        <%= "Organization #{facet.value}  #{facet.count}  posts!" %>
      <% end %>

```
error (tripped up in view at "@search.facet..."

```
undefined method `facet' for
 <Sunspot::Search::PaginatedCollection:0..hash..0>
```

The Search part works fine for all parameters including the text field

adding the facet function is breaking it. Any help appreciated. thanks

**Comment by acprsadmin** [comment]
oops forgot to add ----- using Rails 4.2.3bund Sunspot_rails 2.2 and Sunspot_solr 2.2

**Comment by acprsadmin** [comment]
OK new information. 
I created a replication of the Sunspot Railscast tutorial and got it to work perfectly on another small rails install. The facet block shows up and all appears to work. 

On another rails app on the same laptop is not working when I try to display facets (see above). I've been trying to find out differences between the two. Apparently in the version that works I use 
`<%= debug @search %>` 
in my results page and i get the following:
`<Sunspot::Search:{:fq=>["type:Post"], :q=>"tongues", :fl=>"* score", :qf=>"title_text body_text publish_month_text", :defType=>"edismax", :start=>0, :rows=>30, :facet=>"true", :"f.publish_month_s.facet.mincount"=>1, :"facet.field"=>["publish_month_s", "category_ids_im"], :"f.category_ids_im.facet.mincount"=>1}>`

when I do the same in the larger app (the one i need to work) i get a normal dump of the @search object :

```
--- !ruby/array:Sunspot::Search::PaginatedCollection
internal:
- !ruby/object:Resource
  raw_attributes:
    id: '2'
    submitter: 
    position: 
    orgname: Institute of International Education (IIE)
    submitter_email: 
    submitter_phone: 
    mepi_project: E-Mediat
    mepi_project_number: 
    focus_women: t
    focus_youth: 
    published_at: '2016-02-29 00:00:00'
    nid: '1559'
    number_pages: '30'
    doc_types: Slide Presentation
    materialtype_id: 
    website: ''
    partner_orgs: ''
    presenter: Beth Kanter
    training_event: 'E-Mediat Networking Conference: New Media for the Networked NGO'
    event_date: '2012-03-12 00:00:00'
    language: '1'
    tnid: '0'
    organization_id: '42'
    pid: 
    pnid: 
    tid: 
    series_id: 
    project_id: 
    created_at: '2016-02-11 21:24:06.140596'
    updated_at: '2016-02-11 21:24:06.140596'
    is_featured: 
  attributes: !ruby/object:ActiveRecord::AttributeSet
    attributes: !ruby/object:ActiveRecord::LazyAttributeHash
      types: &5
        id: &3 !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer
          precision: 
          scale: 
          limit: 
          range: !ruby/range
            begin: -2147483648
            end: 2147483648
            excl: true
```
etc etc 


why the differences? Both seem to be conducting the searches correctly.  The 
`@search.facet() `
is not recognized by the larger app. 
thanks for any help.
