### ISSUE TITLE
Second Solr Instance is Locked on Startup

### ISSUE THREAD

**Issue by JackGalore** [sunspot/sunspot#811]
I've been trying to figure out a workflow where my Minitest suite will launch a second Solr instance for feature tests even if the development instance is running. However, I'm running into issues just getting the servers to start (i.e. when I start them outside of testing). 

To start my servers I'm using: 

```
RAILS_ENV=development bin/rake sunspot:solr:start
RAILS_ENV=test bin/rake sunspot:solr:start
```

However, whichever server starts _second_ becomes locked. Any attempt to access the server in tests or just in development yields this error:

```
RSolr::Error::Http - 500 Internal Server Error
Error:     {msg=SolrCore 'test& 'is not available due to init failure: Index locked for write for core 'test'. Solr now longer supports forceful unlocking via 'unlockOnStartup'. Please verify locks manually!,trace=org.apache.solr.common.SolrException: SolrCore 'test' is not available due to init failure: Index locked for write for core 'test'. Solr now longer supports forceful unlocking via 'unlockOnStartup'. Please verify locks manually!
    at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:974)
    at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:250)
    at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:417)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:214)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:179)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)

URI: http://localhost:8981/solr/test/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add/>"
```

I've searched around for issues related to locking but I can't find any where the problem is having two servers running. My setup is:

Rails (5.0.0.1)
sunspot (2.2.5)
sunspot_rails (2.2.5)
sunspot_solr (2.2.5)
ruby 2.3.1p112

My `sunspot.yml` is:

```
production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
```

And finally, `solr.xml`

```
<solr>

  <solrcloud>

    <str name="host">${host:}</str>
    <int name="hostPort">${jetty.port:8983}</int>
    <str name="hostContext">${hostContext:solr}</str>

    <bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>

    <int name="zkClientTimeout">${zkClientTimeout:30000}</int>
    <int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
    <int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>

  </solrcloud>

  <shardHandlerFactory name="shardHandlerFactory"
    class="HttpShardHandlerFactory">
    <int name="socketTimeout">${socketTimeout:600000}</int>
    <int name="connTimeout">${connTimeout:60000}</int>
  </shardHandlerFactory>

</solr>
```

Thank you so much in advance!

**Comment by antongudkov** [comment]
Try to to change `lockType` in `solr/configsets/sunspot/conf/solrconfig.xml` (or wherever you have this file):
from
```
<lockType>${solr.lock.type:simple}</lockType>
```

to
```
<lockType>simple</lockType>
```

This change helped me to solve the issue.

**Comment by 1v** [comment]
Changing lock type did not helped me. I ended by just setting same `port`/`path` for dev and prod.

**Comment by AlejandroFernandesAntunes** [comment]
Worked with the solution above. I just changed the port on to be the same.
Also on my feature tests, each time I used FactoryGirl create I had to add a Sunspot.commit line below. Don't know why but Sunspot is not committing unless explicitly telling it to do so.

**Comment by karanvalecha** [comment]
Here's what works for me:

```ruby
RAILS_ENV=your-env rake sunspot:solr:stop
```

```bash
find . | grep write.lock
```

Delete all the `write.lock` files in `solr/your_env/data/index/` directory(strange you have to do it for all)

```ruby
RAILS_ENV=your-env rake sunspot:solr:start
```

**Comment by jakewendt** [comment]
Seems that "start" creates a write.lock in all `solr/*/data/index/` dirs regardless of environment you are using, `find solr -name write.lock`. Using `bundle exec rake sunspot:solr:run` is more informative. It seems to fail starting for one environment when **any** lock exists. I may be misinterpreting.

Nevertheless, if all instances are stopped...
Running
```
find solr -name write.lock -exec rm {} \;
RAILS_ENV=development bundle exec rake sunspot:solr:run
```
successfully starts for me.

Then, in a separate window, running `RAILS_ENV=test bundle exec rake sunspot:solr:run` kinda fails for me so `Ctrl-C` and then, instead, running 
```
find solr -name write.lock -exec rm {} \;
RAILS_ENV=test bundle exec rake sunspot:solr:run
```
successfully starts the second instance.

It works, but doesn't seem right to me.

**Comment by jakewendt** [comment]
New solution fresh from scratch
```
/bin/rm -rf config/sunspot.yml solr/
rails generate sunspot_rails:install
```

Edit `config/sunspot.yml` to have development and test share the same port.
```
production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/test
```

Run **just one instance** `bundle exec rake sunspot:solr:run`

Reindex your development data `bundle exec rake sunspot:solr:reindex`

Feel free to open your browser to `http://localhost:8982/solr/#/`

Both development, test as well as "default" are there. 

Start your development server `rails s` and open `http://localhost:3000/` and browse somewhere to demonstrate function. 

And testing seems to still work `bundle exec rake ; bundle exec autotest`

**Comment by petran** [comment]
I have a similar error
 
    RSolr::Error::Http - 500 Internal Server Error
						Error:     {msg=SolrCore &apos;default&apos; is not available due to init failure: Index locked for write for core &apos;default&apos;. Solr now longer supports forceful unlocking via &apos;unlockOnStartup&apos;. Please verify locks manually!,trace=org.apache.solr.common.SolrException: SolrCore &apos;default&apos; is not available due to init failure: Index locked for write for core &apos;default&apos;. Solr now longer supports forceful unlocking via &apos;unlockOnStartup&apos;. Please verify locks manually!

**Comment by mlh758** [comment]
You can stub the session:

```
  # Stubbing for sunspot
  begin
    require 'sunspot/rails/spec_helper'

    config.before(:each) do
      ::Sunspot.session = ::Sunspot::Rails::StubSessionProxy.new(::Sunspot.session)
    end

    config.after(:each) do
      ::Sunspot.session = ::Sunspot.session.original_session
    end

  rescue LoadError # This prevents everything from failing if the project doesn't use sunspot :)
  end
```

which takes Solr out of the equation during tests. If you are trying to run integration tests, you could just switch the path to the core during testing:

sunspot.yml:
```
default: &default
    hostname: <%= ENV['SOLR_HOSTNAME'] || 'localhost' %>
    port: 8983
    path: /solr/app

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/test
```

Then one solr instance can serve both environments.
